name: Releases


on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: "The repository reference to checkout"
        required: false
        type: string
  push:
    branches: [ main ]
  release:
    types: [ created ]


concurrency:
  group: "Releases: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


jobs:

  tests:
    uses: ./.github/workflows/run_tests.yml
    permissions:
      contents: read
      checks: write

  publish-maven:
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/run_publish_maven.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
